### PR TITLE
Add pinMode type

### PR DESCRIPTION
**Pull request by ogatatsu**
Add the following pinMode types
- INPUT_SENSE_HIGH
- INPUT_SENSE_LOW
- OUTPUT_S0S1
- OUTPUT_H0S1
- OUTPUT_S0H1
- OUTPUT_H0H1
- OUTPUT_D0S1
- OUTPUT_D0H1
- OUTPUT_S0D1
- OUTPUT_H0D1

### CODE REVIEW

**Comment by ogatatsu** [comment]
The source of the firmata library is written assuming that the definition of INPUT is 0 and OUTPUT is 1, so I modified it to maintain compatibility.

**Review by hathach — APPROVED** [review]
Thank you for the PR, it is indeed much easier to work with other libraries, since they expect the norm value. It is a bit more work with switch case, but compatible is more important.

**Comment by selman-nus** [comment]
Hi, which file should I include to be able to use OUTPUT_H0H1 in my sketch? I included <bluefruit.h> but Arduino is not happy yet.

```
error: 'OUTPUT_H0H1' was not declared in this scope
   50 |     pinMode(20, OUTPUT_H0H1);
      |                 ^~~~~~~~~~~
exit status 1
'OUTPUT_H0H1' was not declared in this scope

```

**Comment by selman-nus** [comment]
I tried several files to include but it didn't work. So I copied the snippet to test it out. 
.
Here is my code on setup(). I connected a sensor and tried to draw 9-10 ma of current. I measured current flow using a multimeter and I could only get 6mA from the pin. So I don't think the below snippet is functional. 
.
Please let me know if I am missing something. 


```
    uint32_t ulPin = 23;
    ulPin = g_ADigitalPinMap[ulPin];
    NRF_GPIO_Type * port = nrf_gpio_pin_port_decode(&ulPin);
    port->PIN_CNF[ulPin] = ((uint32_t)GPIO_PIN_CNF_DIR_Output       << GPIO_PIN_CNF_DIR_Pos)
                           | ((uint32_t)GPIO_PIN_CNF_INPUT_Disconnect << GPIO_PIN_CNF_INPUT_Pos)
                           | ((uint32_t)GPIO_PIN_CNF_PULL_Disabled    << GPIO_PIN_CNF_PULL_Pos)
                           | ((uint32_t)GPIO_PIN_CNF_DRIVE_H0H1       << GPIO_PIN_CNF_DRIVE_Pos)
                           | ((uint32_t)GPIO_PIN_CNF_SENSE_Disabled   << GPIO_PIN_CNF_SENSE_Pos);
                           
    digitalWrite(ulPin, HIGH);
    delay(50);
```
.
I should be able to draw more than 10mA with the high drive setting.

image

pg156 nRF52832 Product Specification pdf

**Comment by ogatatsu** [comment]
Hi

> Hi, which file should I include to be able to use OUTPUT_H0H1 in my sketch? I included <bluefruit.h> but Arduino is not happy yet.

It still doesn't work in version 0.21.0. I think it will work from the next version. 

>  Please let me know if I am missing something.

How about this snippet? 

```
    uint32_t ulPin = 23;
    uint32_t rawPin = g_ADigitalPinMap[ulPin];
    NRF_GPIO_Type * port = nrf_gpio_pin_port_decode(&rawPin);
    port->PIN_CNF[rawPin] = ((uint32_t)GPIO_PIN_CNF_DIR_Output       << GPIO_PIN_CNF_DIR_Pos)
                           | ((uint32_t)GPIO_PIN_CNF_INPUT_Disconnect << GPIO_PIN_CNF_INPUT_Pos)
                           | ((uint32_t)GPIO_PIN_CNF_PULL_Disabled    << GPIO_PIN_CNF_PULL_Pos)
                           | ((uint32_t)GPIO_PIN_CNF_DRIVE_H0H1       << GPIO_PIN_CNF_DRIVE_Pos)
                           | ((uint32_t)GPIO_PIN_CNF_SENSE_Disabled   << GPIO_PIN_CNF_SENSE_Pos);
                           
    digitalWrite(ulPin, HIGH);
```

**Comment by selman-nus** [comment]
Hi @ogatatsu ,
Thanks for the reply, I tried your snippet with my sensor again and it didn't work. The sensor is using just several mA on average but probably has high spikes on the startup. So I will test this snippet again in a more controlled way. 
.
Is this repo not being updated anymore? I have seen your PR for spi.setpin() function and it is also not included in the current release. It seems like @hathach is not supporting here anymore. 
.
Can you tell me how can I use your unreleased PRs? Is there a way to download them into my library? 
I hope changing individual files one by one is not the only option for this purpose.

**Comment by selman-nus** [comment]
@ladyada 
Is it possible to get support on this issue?

**Comment by ladyada** [comment]
this isnt an issue, its a PR - if you hav an issue you can open one, we have no guarantees of support for PRs made by others. you should probably just use a transistor to power the sensor not a pin.

**Comment by selman-nus** [comment]
@ladyada 
Sorry i should have asked more clearly, I meant the issue just mentioned by @jpconstantineau , issue number #600 . 
.
I already posted a message on that issue so i didn't wanted to double my message.  
.
If this issue can be solved, we can use master branch directly in our projects with updated libraries.

**Comment by wb8wka** [comment]
I have a similar issue with hardware PWM.   In this case, _I am using a transistor (Mosfet)_ to drive my load, however, due to the relatively high input capacitance of the MOSFET, I'd like to use OUTPUT_H0H1 to decrease my slew rate.

I tried the method @ogatatsu suggested as well as:


 nrf_gpio_cfg(ulPin,
               NRF_GPIO_PIN_DIR_OUTPUT,
               NRF_GPIO_PIN_INPUT_CONNECT,
               NRF_GPIO_PIN_NOPULL,
               NRF_GPIO_PIN_H0H1,
               NRF_GPIO_PIN_NOSENSE);     // Hopefully this overrides the pinMode(pin, OUTPUT); in HardwarePWM.cpp

from:    #361     use high drive H0H1 for SCK and MOSI for better performance at highseed 32Mhz 

and it compiles and runs as before, with no change in the slew rate. I did check hardwarePWM.ccp to see if did another pinMode and it didn't appear to

Any other thoughts for workarounds?


Jeff

```
 void init_pwm(void)
 {
  uint32_t ulPin = IR_LED;     // Pin 11
  HwPWM0.addPin(IR_LED);   

 nrf_gpio_cfg(ulPin,
               NRF_GPIO_PIN_DIR_OUTPUT,
               NRF_GPIO_PIN_INPUT_CONNECT,
               NRF_GPIO_PIN_NOPULL,
               NRF_GPIO_PIN_H0H1,
               NRF_GPIO_PIN_NOSENSE);     // Hopefully this overrides the pinMode(pin, OUTPUT); in HardwarePWM.cpp

  HwPWM0.begin();
  HwPWM0.setResolution(6);
  HwPWM0.setClockDiv(PWM_PRESCALER_PRESCALER_DIV_1); // freq = 16Mhz
  HwPWM0.setMaxValue(35);
 }
```
